name: MAUI Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads for Android
        run: dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore Grocery.App/Grocery.App.csproj

      - name: Build Android project
        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release --no-restore --no-build --verbosity normal

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: '**/bin/Release/net8.0-android/'
